<a href="https://colab.research.google.com/github/devrasmeriya/Machine-Learning-Projects/blob/main/NLP_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data=pd.read_csv('/content/train.csv')
data.head()

id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

In [ ]:
data.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

In [ ]:
data.duplicated().sum()

0

In [ ]:
x=data['tweet']
y=data['label']

In [ ]:
import spacy
import string
nlp=spacy.load('en_core_web_sm')
punct=string.punctuation
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
from spacy.lang.en.stop_words import STOP_WORDS
stopwords=list(STOP_WORDS)
type(stopwords)

list

In [ ]:
def cleaned_data(sentence):
  doc=nlp(sentence)
  lines=[]
  for tokens in doc:  
    if str(tokens) not in stopwords and str(tokens) not in [punct,'...',':)','^^','#']:
       lines.append(tokens.lower_)
  return lines


In [ ]:
# clean_x=x.apply(lambda a:cleaned_data(a))

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier,LogisticRegression

In [ ]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=.20,random_state=0,stratify=y)

In [ ]:
# tfid=TfidfVectorizer(tokenizer=cleaned_data,stop_words='english')
# tfid.fit(train_x,train_y)

In [ ]:
# tfid.fit_transform(train_x,train_y)

In [ ]:
pipe1=Pipeline([('tfid',TfidfVectorizer(tokenizer=cleaned_data,stop_words='english')),('rfc',RandomForestClassifier(random_state=0))])
pipe2=Pipeline([('tfid',TfidfVectorizer(tokenizer=cleaned_data,stop_words='english')),('svc',LinearSVC())])
pipe3=Pipeline([('tfid',TfidfVectorizer(tokenizer=cleaned_data,stop_words='english')),('multi',MultinomialNB())])
pipe4=Pipeline([('tfid',TfidfVectorizer(tokenizer=cleaned_data,stop_words='english')),('logi',LogisticRegression())])
pipe5=Pipeline([('tfid',TfidfVectorizer(tokenizer=cleaned_data,stop_words='english')),('sgd',SGDClassifier())])

In [ ]:
pipe1.fit(train_x,train_y)
pipe2.fit(train_x,train_y)
pipe3.fit(train_x,train_y)
pipe4.fit(train_x,train_y)
pipe5.fit(train_x,train_y)


/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['nt'] not in stop_words.
  'stop_words.' % sorted(inconsistent))
/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['nt'] not in stop_words.
  'stop_words.' % sorted(inconsistent))
/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['nt'] not in stop_words.
  'stop_words.' % sorted(inconsistent))
/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['nt'] not in stop

Pipeline(memory=None,
         steps=[('tfid',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words='english', strip_accents=None,
                                 sublinear_tf=False,
                                 token_patte...
                 SGDClassifier(alpha=0.0001, average=False, class_weight=None,
                               early_stopping=False, epsilon=0.1, eta0=0.0,
                               fit_intercept=True, l1_ratio=0.15,
                               learning_rate='optimal', loss='hinge',
           

In [ ]:
pre1=pipe1.predict(test_x)
pre2=pipe2.predict(test_x)
pre3=pipe3.predict(test_x)
pre4=pipe4.predict(test_x)
pre5=pipe5.predict(test_x)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(test_y,pre1))
print(confusion_matrix(test_y,pre1))

0.8661616161616161
[[1099   80]
 [ 132  273]]


In [ ]:
print(accuracy_score(test_y,pre2))
print(confusion_matrix(test_y,pre2))

0.8768939393939394
[[1088   91]
 [ 104  301]]


In [ ]:
print(accuracy_score(test_y,pre3))
print(confusion_matrix(test_y,pre3))

0.8402777777777778
[[1159   20]
 [ 233  172]]


In [ ]:
print(accuracy_score(test_y,pre4))
print(confusion_matrix(test_y,pre4))

0.8674242424242424
[[1110   69]
 [ 141  264]]


In [ ]:
print(accuracy_score(test_y,pre5))
print(confusion_matrix(test_y,pre5))

0.8819444444444444
[[1075  104]
 [  83  322]]


In [ ]:
test=pd.read_csv('/content/test.csv')
test.head()

In [ ]:
sample=pd.read_csv('/content/sample_submission_LnhVWA4.csv')
sample.head()

In [ ]:
test.isnull().sum()

In [ ]:
ans5=pipe5.predict(test['tweet'])
ans2=pipe2.predict(test['tweet'])

In [ ]:
sample['label']=ans2

In [ ]:
sample.to_csv('sample5')


In [ ]:
sample.to_csv('samples2')

In [ ]:
# def cleaned_data(sentence):
#     doc=nlp(sentence)
    
#     tokens=[]
#     for token in doc:
#         if token.lemma_ !="-PRON-":
#             temp=token.lemma_.lower().strip()
#         else:
#             temp=token.lower_
#         tokens.append(temp)
        
#     clean=[]
#     for token in tokens:
#         if token not in stopwords and token  not in [punct,'...', '.']:
#             clean.append(token)
#     return clean


In [ ]:
# clean_x=x.apply(lambda a:cleaned_data(a))
import pandas as pd
train=pd.read_csv('/content/train.csv')
train.head()
test=pd.read_csv('/content/test.csv')
test.head()

id                                              tweet
0  7921  I hate the new #iphone upgrade. Won't let me d...
1  7922  currently shitting my fucking pants. #apple #i...
2  7923  I'd like to puts some CD-ROMS on my iPad, is t...
3  7924  My ipod is officially dead. I lost all my pict...
4  7925  Been fighting iTunes all night! I only want th...

In [ ]:
puncts = [',', '.', '"', ':', ')', '(', '-', '!', '?', '|', ';', "'", '$', '&', '/', '[', ']', '>', '%', '=', '#', '*', '+', '\\', '•',  '~', '@', '£', 
 '·', '_', '{', '}', '©', '^', '®', '`',  '<', '→', '°', '€', '™', '›',  '♥', '←', '×', '§', '″', '′', 'Â', '█', '½', 'à', '…', 
 '“', '★', '”', '–', '●', 'â', '►', '−', '¢', '²', '¬', '░', '¶', '↑', '±', '¿', '▾', '═', '¦', '║', '―', '¥', '▓', '—', '‹', '─', 
 '▒', '：', '¼', '⊕', '▼', '▪', '†', '■', '’', '▀', '¨', '▄', '♫', '☆', 'é', '¯', '♦', '¤', '▲', 'è', '¸', '¾', 'Ã', '⋅', '‘', '∞', 
 '∙', '）', '↓', '、', '│', '（', '»', '，', '♪', '╩', '╚', '³', '・', '╦', '╣', '╔', '╗', '▬', '❤', 'ï', 'Ø', '¹', '≤', '‡', '√']
import re
# Code to replace punctuation marks with whitespace 
def clean_text(x):
    x = str(x)
    for punct in puncts:
        if punct in x:
            x = x.replace(punct, ' ')
    return x

# Remove URL's from train and test datasets
train['clean_tweet'] = train['tweet'].apply(lambda x: re.sub(r'http\S+', '', x))
test['clean_tweet'] = test['tweet'].apply(lambda x: re.sub(r'http\S+', '', x))

# Remove user handles @
train['clean_tweet'] = train['clean_tweet'].apply(lambda x: re.sub("@[\w]*", '', x))
test['clean_tweet'] = test['clean_tweet'].apply(lambda x: re.sub("@[\w]*", '', x))

# Remove punctuation marks
train['clean_tweet'] = train['clean_tweet'].apply(lambda x: clean_text(x))
test['clean_tweet'] = test['clean_tweet'].apply(lambda x: clean_text(x))

# Convert text to lowercase
train['clean_tweet'] = train['clean_tweet'].str.lower()
test['clean_tweet'] = test['clean_tweet'].str.lower()

# Remove numbers
train['clean_tweet'] = train['clean_tweet'].str.replace("[0-9]", " ")
test['clean_tweet'] = test['clean_tweet'].str.replace("[0-9]", " ")

# Remove whitespaces
train['clean_tweet'] = train['clean_tweet'].apply(lambda x:' '.join(x.split()))
test['clean_tweet'] = test['clean_tweet'].apply(lambda x: ' '.join(x.split()))

# Function to lemmatize the tokens to their basic forms to normalize the tweet text
# and focus on key words for the classification tasks

def lemmatization(texts):
    output = []
    for i in texts:
        s = [token.lemma_ for token in nlp(i)]
        output.append(' '.join(s))
    return output

# Record the time to lemmatize the tweets and converting them into vectors using spaCy


# Lemmatise the tokens
train['clean_tweet'] = lemmatization(train['clean_tweet'])
train['clean_tweet'] = train['clean_tweet'].str.replace("-PRON-", "")
test['clean_tweet'] = lemmatization(test['clean_tweet'])
test['clean_tweet'] = test['clean_tweet'].str.replace("-PRON-", "")

In [ ]:
# tfid=TfidfVectorizer(stop_words='english')
# train['clean_tweet']=tfid.fit_transform(train['clean_tweet'])
# test['clean_tweet']=tfid.fit_transform(test['clean_tweet'])

In [ ]:
pipe5=Pipeline([('tfid',TfidfVectorizer(stop_words='english')),('sgd',SGDClassifier())])
pipe5.fit(train['clean_tweet'],train['label'])

Pipeline(memory=None,
         steps=[('tfid',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words='english', strip_accents=None,
                                 sublinear_tf=False,
                                 token_patte...
                 SGDClassifier(alpha=0.0001, average=False, class_weight=None,
                               early_stopping=False, epsilon=0.1, eta0=0.0,
                               fit_intercept=True, l1_ratio=0.15,
                               learning_rate='optimal', loss='hinge',
           

In [ ]:
ans=pipe5.predict(test['clean_tweet'])

In [ ]:
sample=pd.read_csv('/content/sample_submission_LnhVWA4.csv')
sample['label']=ans

In [ ]:
sample.to_csv('final')