<a href="https://colab.research.google.com/github/devrasmeriya/Machine-Learning-Projects/blob/main/twitter__sentiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
train=pd.read_csv('/content/train_E6oV3lV.csv')
test=pd.read_csv('/content/test_tweets_anuFYb8.csv')
x=train['tweet']
y=train['label']
import string 
punct=string.punctuation
from spacy.lang.en.stop_words import STOP_WORDS
stopwords=list(STOP_WORDS)

In [ ]:
train_0=train[train['label']==0]
train_1=train[train['label']==1]

In [ ]:
train_0=train_0.sample(len(train_1),random_state=42)
new=train_0.append(train_1)
x=new['tweet']
y=new['label']

In [ ]:
import en_core_web_sm
import re

nlp = en_core_web_sm.load()

In [ ]:
def cleaned_data(sentence):
    doc=nlp(sentence)
    lines=[]
    for tokens in doc:
      if str(tokens).isalpha():
        if str(tokens) not in stopwords and str(tokens) not in [punct,'...','@','^^^',',','   ', '.','#', '"', ':', ')', '(', '-', '!', '?', '|', ';', "'", '$', '&', '/', '[', ']', '>', '%', '=', '#', '*', '+', '\\', '•',  '~', '@', '£', 
'·', '_', '{', '}', '©', '^', '®', '`',  '<', '→', '°', '€', '™', '›',  '♥', '←', '×', '§', '″', '′', 'Â', '█', '½', 'à', '…', 
'“', '★', '”', '–', '●', 'â', '►', '−', '¢', '²', '¬', '░', '¶', '↑', '±', '¿', '▾', '═', '¦', '║', '―', '¥', '▓', '—', '‹', '─', 
'▒', '：', '¼', '⊕', '▼', '▪', '†', '■', '’', '▀', '¨', '▄', '♫', '☆', 'é', '¯', '♦', '¤', '▲', 'è', '¸', '¾', 'Ã', '⋅', '‘', '∞', 
'∙', '）', '↓', '、', '│', '（', '»', '，', '♪', '╩', '╚', '³', '・', '╦', '╣', '╔', '╗', '▬', '❤', 'ï', 'Ø', '¹', '≤', '‡', '√']:
            tokens =tokens.lemma_
            tokens=str(tokens).replace('@',"")
            ttokens=str(tokens).replace('#','a')
            tokens=str(tokens).replace('?',"")
            tokens= re.sub(r'http\S+', '', tokens)
            tokens= re.sub("@[\w]*", '', tokens)
            tokens=tokens.lower()

            lines.append(tokens)
    return lines   
        

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier,LogisticRegression
from sklearn.naive_bayes import GaussianNB

In [ ]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=.2,random_state=42,stratify=y)

In [ ]:
pipe=Pipeline([('tfid',TfidfVectorizer(tokenizer=cleaned_data)),('rfc',SGDClassifier())])
pipe

Pipeline(memory=None,
         steps=[('tfid',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(...
                 SGDClassifier(alpha=0.0001, average=False, class_weight=None,
                               early_stopping=False, epsilon=0.1, eta0=0.0,
                               fit_intercept=True, l1_ratio=0.15,
                               learning_rate='optimal', loss='hinge',
           

In [ ]:
pipe.fit(train_x,train_y)

Pipeline(memory=None,
         steps=[('tfid',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(...
                 SGDClassifier(alpha=0.0001, average=False, class_weight=None,
                               early_stopping=False, epsilon=0.1, eta0=0.0,
                               fit_intercept=True, l1_ratio=0.15,
                               learning_rate='optimal', loss='hinge',
           

In [ ]:
pre=pipe.predict(test_x)

In [ ]:
confusion_matrix(test_y,pre),accuracy_score(test_y,pre),f1_score(test_y,pre)

(array([[385,  64],
        [ 64, 384]]), 0.8573021181716833, 0.8571428571428571)

In [ ]:
# ans=pipe.predict(test['tweet'])
# ans

In [ ]:
pipe=Pipeline([('tfid',TfidfVectorizer(tokenizer=cleaned_data)),('rfc',LogisticRegression(C=1000))])
pipe.fit(train_x,train_y)
pre=pipe.predict(test_x)
confusion_matrix(test_y,pre),accuracy_score(test_y,pre),f1_score(test_y,pre)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


(array([[375,  74],
        [ 58, 390]]), 0.8528428093645485, 0.8552631578947368)

In [ ]:
pipe=Pipeline([('tfid',TfidfVectorizer(tokenizer=cleaned_data)),('rfc',RandomForestClassifier(n_estimators=400))])
pipe.fit(train_x,train_y)
pre=pipe.predict(test_x)
confusion_matrix(test_y,pre),accuracy_score(test_y,pre),f1_score(test_y,pre)

(array([[397,  52],
        [ 90, 358]]), 0.8416945373467113, 0.8344988344988346)

In [ ]:
sample=pd.read_csv('/content/sample_submission_gfvA5FD.csv')

In [ ]:
sample['label']=ans

In [ ]:
sample.to_csv('predictions1')

In [ ]:
test

id                                              tweet
0      31963  #studiolife #aislife #requires #passion #dedic...
1      31964   @user #white #supremacists want everyone to s...
2      31965  safe ways to heal your #acne!!    #altwaystohe...
3      31966  is the hp and the cursed child book up for res...
4      31967    3rd #bihday to my amazing, hilarious #nephew...
...      ...                                                ...
17192  49155  thought factory: left-right polarisation! #tru...
17193  49156  feeling like a mermaid 😘 #hairflip #neverre...
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158  happy, at work conference: right mindset leads...
17196  49159  my   song "so glad" free download!  #shoegaze ...

[17197 rows x 2 columns]