In [1]:
import pandas as pd

In [2]:
import numpy as np

test_data=pd.read_csv('F:/test_8i3B3FC.csv')
test_data['ID']= test_data['ID'].sort_values( ignore_index=True)

data=pd.read_csv('F:/train_NIR5Yl1.csv')



data.head()
data.isnull().sum()

cat=pd.get_dummies(data['Tag'])
cat=cat.drop(['a'],axis=1)
data=data.join(cat)
data=data.drop(['Tag','ID','Username'],axis=1)
data=data.sample(frac =.2 ,weights='Views',random_state=1)

In [3]:
test_data.isnull().sum()
cat=pd.get_dummies(test_data['Tag'])
cat=cat.drop(['a'],axis=1)
test_data=test_data.join(cat)
test_data=test_data.drop(['Tag','ID','Username'],axis=1)


In [4]:

x=data.drop('Upvotes',axis=1)
y=data['Upvotes']


In [5]:

from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y =train_test_split(x,y,test_size=.2,random_state=0)
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
train_x=ss.fit_transform(train_x)
test_x=ss.transform(test_x)
test_data=ss.transform(test_data)

In [6]:

test_data

array([[-0.1152927 , -0.62140182, -0.37494228, ..., -0.13751023,
        -0.24985913, -0.11962383],
       [ 0.62221523, -0.06284041, -0.56201387, ..., -0.13751023,
        -0.24985913, -0.11962383],
       [-0.29972832, -0.99377609, -0.44881929, ..., -0.13751023,
        -0.24985913, -0.11962383],
       ...,
       [-0.31896154, -0.24902754, -0.22852668, ..., -0.13751023,
        -0.24985913, -0.11962383],
       [-0.32908634, -0.62140182, -0.51619453, ..., -0.13751023,
        -0.24985913, -0.11962383],
       [-0.31063496, -0.80758895, -0.50028086, ..., -0.13751023,
        -0.24985913, -0.11962383]])

In [7]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(random_state=0)
rfr.fit(train_x,train_y)


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [8]:
pred=rfr.predict(test_x)
pred


array([3.327000e+01, 4.207021e+04, 1.859780e+03, ..., 1.562600e+02,
       3.500900e+02, 7.007000e+01])

In [9]:
test_y

309762       21.0
168582    56460.0
218913     1949.0
155898     3017.0
198607     2374.0
           ...   
169873      136.0
318636      910.0
308310      243.0
48117       289.0
267768       47.0
Name: Upvotes, Length: 13202, dtype: float64

In [10]:
from sklearn.metrics import mean_squared_error
mean_squared_error(test_y,pred)

5033829.93499488

In [11]:
predictions =rfr.predict(test_data)

In [12]:
predictions

array([248.92,  68.07,  54.87, ..., 102.79,  18.39,  31.17])

In [21]:
sample=pd.read_csv('F:/sample_submission_OR5kZa5.csv')
sample['Upvotes']=predictions


ID  Upvotes
0            7   248.92
1            9    68.07
2           12    54.87
3           13    11.02
4           16   312.27
...        ...      ...
141443  471473    19.45
141444  471481   165.36
141445  471486   102.79
141446  471487    18.39
141447  471488    31.17

[141448 rows x 2 columns]

In [28]:
sample.drop

ID  Upvotes
0            7   248.92
1            9    68.07
2           12    54.87
3           13    11.02
4           16   312.27
...        ...      ...
141443  471473    19.45
141444  471481   165.36
141445  471486   102.79
141446  471487    18.39
141447  471488    31.17

[141448 rows x 2 columns]

In [30]:
# Save the final submission file
sample.to_csv('F:\submission.csv')

In [15]:
# test_data=pd.read_csv('F:/test_8i3B3FC.csv')
# data=pd.read_csv('F:/train_NIR5Yl1.csv')
# data.head()
# data.isnull().sum()
# cat=pd.get_dummies(data['Tag'])
# cat=cat.drop(['a'],axis=1)
# data=data.join(cat)
# data=data.drop(['Tag','ID','Username'],axis=1)
# data=data.sample(frac =.2 ,weights='Views',random_state=1)
# x=data.drop('Upvotes',axis=1)
# y=data['Upvotes']
# x.shape
# from sklearn.model_selection import train_test_split
# train_x,test_x,train_y,test_y =train_test_split(x,y,test_size=.2,random_state=0)

In [16]:
import numpy as np
import pandas as pd
from sklearn import datasets

from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [17]:
# correlation = data.corr(method='pearson')
# columns = correlation.nlargest(10, 'price').index
# columns

In [18]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

In [19]:
pipelines = []
pipelines.append(('ScaledLR', Pipeline([('Scaler', StandardScaler()),('LR',LinearRegression())])))
pipelines.append(('ScaledLASSO', Pipeline([('Scaler', StandardScaler()),('LASSO', Lasso())])))
pipelines.append(('ScaledEN', Pipeline([('Scaler', StandardScaler()),('EN', ElasticNet())])))
pipelines.append(('ScaledKNN', Pipeline([('Scaler', StandardScaler()),('KNN', KNeighborsRegressor())])))
pipelines.append(('ScaledCART', Pipeline([('Scaler', StandardScaler()),('CART', DecisionTreeRegressor())])))
pipelines.append(('ScaledGBM', Pipeline([('Scaler', StandardScaler()),('GBM', GradientBoostingRegressor())])))
pipelines.append(('ScaledRFR', Pipeline([('Scaler', StandardScaler()),('RFR', RandomForestRegressor())])))

results = []
names = []
for name, model in pipelines:
    kfold = KFold(n_splits=10)
    cv_results = cross_val_score(model, train_x, train_y, cv=kfold, scoring='neg_mean_squared_error')
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

ScaledLR: -43468212.878451 (36847518.186619)
ScaledLASSO: -43468323.899184 (36852642.703987)
ScaledEN: -45823960.239703 (41346919.119907)
ScaledKNN: -22028078.547406 (22652126.856728)
ScaledCART: -14405418.809954 (12681426.016136)


KeyboardInterrupt: 

In [ ]:
from sklearn.metrics import mean_squared_error

scaler = StandardScaler().fit(train_x)
rescaled_X_train = scaler.transform(train_x)
model = RandomForestRegressor(n_jobs=-1,random_state=0,n_estimators=400)
model.fit(rescaled_X_train, train_y)

# transform the validation dataset
rescaled_X_test = scaler.transform(test_x)
predictions = model.predict(rescaled_X_test)
print (mean_squared_error(test_y, predictions))

In [ ]:
compare = pd.DataFrame({'Prediction': predictions, 'Test Data' : Y_test})
compare.head(10)